---
title: "Decender2020"
output: html_document
date: "2025-10-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,posterior,tidybayes,cmdstanr, furrr,futuremap,ordbetareg, future.apply, patchwork,purrr)


invisible(
  lapply(
    list.files(here::here("Analysis", "Functions"), pattern = "\\.[Rr]$", full.names = TRUE),
    source
  )
)
```

## R Markdown

```{r}
df = read.delim(here::here("Data","Decender2020","rawData.txt"), sep = " ") %>% filter(practiceblocks1 == 0,
                                                                                       practiceblocks2 == 0) %>% 
  filter(rt > 0 & resp != -1, include == 1, block > 3) %>%
  filter(!sub %in% c(12,15,21,29)) %>% 
  mutate(conf = ifelse(t2duration == 0,conf+3,conf),
         X  = coh_single,
         ConfidenceRT = NA) %>% 
  mutate(conf = case_when(
    sub == 7 & t2duration == 0 & conf == 4 ~ 6,
    sub == 7 & t2duration == 0 & conf == 6 ~ 4,
    sub == 7 & t2duration == 0 & conf == 1 ~ 6,
    sub == 7 & t2duration == 0 & conf == 3 ~ 4,
    TRUE ~ conf
  )) %>% 
    rename(
    Confidence = conf,
    Y = cor,
    RT = rt,
    subject = sub
  ) %>% 
  mutate(Correct = Y)
```


# bad subjects
```{r, fig.width=10,fig.height=7, message=FALSE, warning=FALSE}
remover(df %>% filter(t2duration == 0))

df %>% filter(t2duration == 0 & subject == 23) %>% ggplot(aes(x = X, y = Y))+
  geom_jitter(width = 0.05, height = 0.1)+
    geom_smooth(method = "glm", 
    method.args = list(family = "binomial"), 
    se = FALSE) 

t2duration0_remover = 23
```

```{r, fig.width=10,fig.height=7, message=FALSE, warning=FALSE}
remover(df %>% filter(t2duration == 1))

```


```{r, fig.width=10,fig.height=7, message=FALSE, warning=FALSE}
remover(df %>% filter(t2duration == 2))
```

```{r, fig.height=7,fig.width=10}
(Group_plot(df %>% filter(t2duration == 0 & !subject %in% t2duration0_remover))+ggtitle("Cohort0") | 
   Group_plot(df %>% filter(t2duration == 1))+ggtitle("Cohort1") |
   Group_plot(df %>% filter(t2duration == 2))+ggtitle("Cohort2"))+
  plot_layout(guides = "collect")&theme(legend.position = "top")
```


```{r, fig.height=7,fig.width=12, message=F, error=F,warning=F}
n_subj <- length(unique(df %>% filter(t2duration == 0 & !subject %in% t2duration0_remover) %>% .$subject))
subject_chunks <- split(1:n_subj, ceiling(seq_along(1:n_subj) / 5))

plots <- lapply(subject_chunks, function(chunk) plot_subjects(df %>% filter(t2duration == 0), chunk, bin = 7))
plots
```


```{r, fig.height=7,fig.width=12, message=F, error=F,warning=F}
n_subj <- length(unique(df %>% filter(t2duration == 1) %>% .$subject))
subject_chunks <- split(1:n_subj, ceiling(seq_along(1:n_subj) / 5))

plots <- lapply(subject_chunks, function(chunk) plot_subjects(df %>% filter(t2duration == 1), chunk, bin = 7))
plots
```


```{r, fig.height=7,fig.width=12, message=F, error=F,warning=F}
n_subj <- length(unique(df %>% filter(t2duration == 2) %>% .$subject))
subject_chunks <- split(1:n_subj, ceiling(seq_along(1:n_subj) / 5))

plots <- lapply(subject_chunks, function(chunk) plot_subjects(df %>% filter(t2duration == 2), chunk, bin = 7))
plots
```


# fit model

```{r}

fit0 = fit_data_copula_rt(df %>% filter(t2duration == 0 & !subject %in% t2duration0_remover) %>% mutate(Confidence = Confidence -3),
                          ACC = T, 
                          "T2_0",
                          modeltype = "pure",
                          conf = "discrete_conf")


fit01 = fit_data_copula_rt(df %>% filter(t2duration == 0 & !subject %in% t2duration0_remover) %>% mutate(Confidence = Confidence -3),
                           ACC = T, 
                           "T2_0",
                           modeltype = "meta_un",
                           conf = "discrete_conf")


fit02 = fit_data_copula_rt(df %>% filter(t2duration == 0 & !subject %in% t2duration0_remover) %>% mutate(Confidence = Confidence -3),
                           ACC = T,
                           "T2_0",
                           modeltype = "meta_un_rt_un",
                           conf = "discrete_conf")


fit0 = fit_data_copula_rt(df %>% filter(t2duration == 1),
                          ACC = T, 
                          "T2_1",
                          modeltype = "pure",
                          conf = "discrete_conf")


fit01 = fit_data_copula_rt(df %>% filter(t2duration == 1),
                           ACC = T, 
                           "T2_1",
                           modeltype = "meta_un",
                           conf = "discrete_conf")


fit02 = fit_data_copula_rt(df %>% filter(t2duration == 1),
                           ACC = T,
                           "T2_1",
                           modeltype = "meta_un_rt_un",
                           conf = "discrete_conf")




fit0 = fit_data_copula_rt(df %>% filter(t2duration == 2),
                          ACC = T, 
                          "T2_1",
                          modeltype = "pure",
                          conf = "discrete_conf")


fit01 = fit_data_copula_rt(df %>% filter(t2duration == 2),
                           ACC = T, 
                           "T2_1",
                           modeltype = "meta_un",
                           conf = "discrete_conf")


fit02 = fit_data_copula_rt(df %>% filter(t2duration == 2),
                           ACC = T,
                           "T2_1",
                           modeltype = "meta_un_rt_un",
                           conf = "discrete_conf")
```


```{r}

n_draws = 10
workers = 15
memory = 5000 * 1024^2

parameters = c("alpha","beta","lapse","rt_int","rt_slope","rt_ndt","rt_prec",
               "conf_int","conf_ACC","conf_entropy","conf_entropy_ACC","c0","c11","conf_prec",
               "rho_p_rt","rho_p_conf","rho_rt_conf")


df_param = as_draws_df(cor$draws(parameters)) %>% 
  select(-contains(".")) %>% 
  mutate(draw = 1:n()) %>% 
        pivot_longer(-draw) %>% 
        extract(name, into = c("variable", "sub"),
                regex = "([a-zA-Z0-9_]+)\\[(\\d+)\\]", convert = TRUE)



# First we select the number of workers and then the memory:
plan(multisession, workers = workers)
options(future.globals.maxSize = memory)

#then the number of subjects
subjects <- unique(df$sub)
# and draws per subject
draws <- 1:n_draws

# Only use the number of draws that the user wants:
dfq = df_param %>% filter(draw %in% draws)

# function to get the draws (goes through subjects and then the draws)
pred_list <- future_lapply(subjects, function(s) {
lapply(draws, function(d) {
  
  # extract parameter vectors (mu, phi, c0 and c1) for that draw and that subject
  params <- dfq %>%
    filter(sub == s, draw == d) %>%
    select(variable, value) %>%
    pivot_wider(names_from = "variable", values_from = "value")
  
  
  data = df %>% filter(sub == s)
  
  psycho_ACC = function(x,alpha,beta,lapse){
    0.5+(0.5*(1-2*lapse))*((tanh(beta*(x-alpha))/2) + 0.5)
  }
  entropy = function(p){
    -p * log(p) - (1-p) * log(1-p)
  }
  
  x = seq(min(df$coh_single), max(df$coh_single), by = 0.1)
  prob = psycho_ACC(x, params$alpha, params$beta, params$lapse)
  
  bin_pred = rbinom(length(prob),1,prob)
  
  rt_mu = params$rt_int + params$rt_slope * entropy(prob)
  rt_ndt = params$rt_ndt
  
  # apply inverse logit and scale
  RT_pred = rlnorm(length(rt_mu),rt_mu,params$rt_prec)+rt_ndt
        
  
  
  conf_dat = data.frame(prob = prob) %>% 
    rowwise() %>% 
    mutate(ACC = list(c(0,1))) %>% unnest()
  
  conf_mu = params$conf_int +
    params$conf_ACC * conf_dat$ACC +
    params$conf_entropy * entropy(conf_dat$prob) +
    params$conf_entropy_ACC * conf_dat$ACC * entropy(conf_dat$prob)

  # Collect the responses from the ordered beta
  confidence_pred = data.frame()
  for(i in 1:length(conf_mu)){
    q = rordbeta(1, mu = brms::inv_logit_scaled(conf_mu[i]),
                 phi = params$conf_prec,
                 cutpoints = c(params$c0, params$c0 + exp(params$c11)))  
    
    dat = data.frame(pred = q, ACC = conf_dat$ACC[i])
    
    confidence_pred = rbind(confidence_pred, dat)
  }
  
  confidence_pred =  confidence_pred %>% mutate(ACC = ifelse(ACC == 1, "Correct","Incorrect")) %>% 
    pivot_wider(names_from = "ACC", values_from = pred) %>% unnest()
  
  predictions = confidence_pred %>% mutate(bin_pred = bin_pred, RT_pred = RT_pred,
                                           x = x, draw = d, sub = s, prob = prob)
  
  
})
},future.seed=TRUE)


# flatten nested list and create a tidy long dataframe
predictions = map_dfr(pred_list, bind_rows)
```





```{r, fig.height=7, fig.width=12}
predictions %>% 
  ggplot() +
  geom_line(aes(x = x, y = prob, group = draw))+
  geom_point(aes(x = x, y = bin_pred, group = draw), position = position_dodge(width = 0.03), alpha = 0.3)+
  facet_wrap(~sub, scales = "free") +
  theme_classic(base_size = 16)


predictions %>% group_by(draw,sub) %>% summarize(p_correct = sum(bin_pred) / n()) %>% 
  ggplot() +
  geom_col(data = df %>% mutate(draw = NA) %>% group_by(sub) %>% summarize(p_correct = sum(cor) / n()),
             aes(x = 1, y = p_correct))+
  geom_point(aes(x = 1,y = p_correct, group = draw), position = position_dodge(width = 0.1), alpha = 0.5)+
  facet_wrap(~sub, scales = "free") +
  theme_classic(base_size = 16)
```


```{r, fig.height=7, fig.width=12}
predictions %>% 
  ggplot() +
  geom_line(aes(x = x, y = RT_pred, group = draw))+
  geom_point(data = df %>% mutate(draw = NA), aes(x = coh_single, y = rt, group = draw))+
  facet_wrap(~sub, scales = "free") +
  theme_classic(base_size = 16)

predictions %>% 
  ggplot() +
  geom_histogram(data = df %>% mutate(draw = NA),
             aes(x = rt, y = after_stat(density)),
             position = "identity",col = "black", alpha = 0.5)+
  geom_density(aes(x = RT_pred, group = draw), alpha = 0.5)+
  facet_wrap(~sub, scales = "free") +
  theme_classic(base_size = 16)
```


```{r, fig.height=7, fig.width=12}
predictions %>% pivot_longer(cols = c("Incorrect","Correct"), values_to = "Confidence",names_to = "Correct") %>% 
  ggplot() +
  geom_line(aes(x = x, y = Confidence, col = (Correct), group = interaction(Correct,draw)))+
  geom_point(data = df %>% mutate(draw = NA) %>% mutate(Correct = ifelse(cor == 1, "Correct","Incorrect")),
             aes(x = coh_single, y = conf / 6, col = (Correct), group = interaction(Correct,draw)))+
  facet_wrap(~sub, scales = "free") +
  theme_classic(base_size = 16)



predictions %>% 
  pivot_longer(cols = c("Incorrect","Correct"), values_to = "Confidence",names_to = "Correct") %>% 
  ggplot() +
  geom_histogram(data = df %>% mutate(draw = NA) %>% mutate(Correct = ifelse(cor == 1, "Correct","Incorrect")),
             aes(x = conf / 6,y = after_stat(density), fill = Correct),
             position = "identity",col = "black", alpha = 0.5)+
  geom_density(aes(x = Confidence, color = Correct, group = interaction(Correct,draw)), alpha = 0.5)+
  facet_wrap(~sub, scales = "free") +
  theme_classic(base_size = 16)

    
```

