---
title: "Decender2020"
output: html_document
date: "2025-10-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,posterior,tidybayes,cmdstanr, furrr,futuremap,ordbetareg, future.apply, patchwork,purrr)


invisible(
  lapply(
    list.files(here::here("Analysis", "Functions"), pattern = "\\.[Rr]$", full.names = TRUE),
    source
  )
)
```

## R Markdown

# Preprocesing

```{r}
df = read.csv(here::here("Data","VMP_extero","raw_hrd.csv")) %>% 
    mutate(DecisionRT = as.numeric(DecisionRT),
           ConfidenceRT = as.numeric(ConfidenceRT),
         Confidence = as.numeric(Confidence),
         ResponseCorrect = as.numeric(ifelse(ResponseCorrect == "1",1,
                                             ifelse(ResponseCorrect == "1.0",1,
                                                    ifelse(ResponseCorrect == "True",1,
                                                           ifelse(ResponseCorrect == "0",0,
                                                                  ifelse(ResponseCorrect == "0.0",0,
                                                                         ifelse(ResponseCorrect == "False",0,NA))))))),
         Decision = ifelse(Decision == "More",1,ifelse(Decision == "Less",0,NA))) %>% 
  mutate(participant_id = as.numeric(as.factor(participant_id))) %>%
  filter(Modality == "Extero") %>% 
  filter(DecisionRT < 8 & DecisionRT > 0.1)%>% 
  select(ResponseCorrect,participant_id,DecisionRT,Decision, Confidence, ConfidenceRT, Alpha,cohort)  %>% drop_na() %>% 
  rename(
    Confidence = Confidence,
    X  = Alpha,
    Y = Decision,
    RT = DecisionRT,
    subject = participant_id
  ) %>% 
  mutate(Correct = ResponseCorrect,
         Confidence = Confidence/100)
```



```{r}
mod = cmdstanr::cmdstan_model(here::here("Stanmodels","ss","SS_Confidence_Standard.stan"))

df1 = df %>% filter(subject == 2)


datastan = list(N = nrow(df1), binom_y = df1$Y,
                RT = df1$RT, Conf = df1$Confidence,
                X = df1$X, minRT = min(df1$RT), ACC = df1$Correct,
                starts = 1, ends = nrow(df1))


cor <-mod$sample(
    data = datastan,
    refresh = 10,
    iter_sampling = 500,
    iter_warmup = 500,
    adapt_delta = 0.95,
    max_treedepth = 12,
    init  = 0,
    parallel_chains = 4)


cor$summary(c("gm","rho_p_rt","rho_p_conf","rho_rt_conf"))


```

