---
title: "Decender2020"
output: html_document
date: "2025-10-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,posterior,tidybayes,cmdstanr, furrr,ordbetareg, future.apply, patchwork,purrr, bayesplot)


invisible(
  lapply(
    list.files(here::here("Analysis", "Functions"), pattern = "\\.[Rr]$", full.names = TRUE),
    source
  )
)
```

## R Markdown

# Preprocesing

```{r}
df = read.csv(here::here("Data","VMP_extero","raw_hrd.csv")) %>% 
    mutate(DecisionRT = as.numeric(DecisionRT),
           ConfidenceRT = as.numeric(ConfidenceRT),
         Confidence = as.numeric(Confidence),
         ResponseCorrect = as.numeric(ifelse(ResponseCorrect == "1",1,
                                             ifelse(ResponseCorrect == "1.0",1,
                                                    ifelse(ResponseCorrect == "True",1,
                                                           ifelse(ResponseCorrect == "0",0,
                                                                  ifelse(ResponseCorrect == "0.0",0,
                                                                         ifelse(ResponseCorrect == "False",0,NA))))))),
         Decision = ifelse(Decision == "More",1,ifelse(Decision == "Less",0,NA))) %>% 
  mutate(participant_id = as.numeric(as.factor(participant_id))) %>%
  filter(Modality == "Extero",
         session == 1) %>% 
  filter(DecisionRT < 8 & DecisionRT > 0.1)%>% 
  select(ResponseCorrect,participant_id,DecisionRT,Decision, Confidence, ConfidenceRT, Alpha,cohort)  %>% drop_na() %>% 
  rename(
    Confidence = Confidence,
    X  = Alpha,
    Y = Decision,
    Correct = ResponseCorrect,
    RT = DecisionRT,
    subject = participant_id
  ) %>% 
  mutate(Confidence = Confidence/100,
         resp = Y)

```

# bad subjects
```{r, fig.width=10,fig.height=7, message=FALSE, warning=FALSE}
remover(df %>% filter(cohort == "vmp1"))
removers_vmp1 = c("16","167")


remover(df %>% filter(cohort == "vmp2"))
removers_vmp2 = c("233","258","263","270","275","287","288","298","300","313","326","346","298","326","397","448","495","470","546")

```


```{r, fig.height=7,fig.width=12, message=F, error=F,warning=F}
n_subj <- length(unique(df %>% filter(cohort == "vmp1"& !subject %in% removers_vmp1) %>% .$subject))
subject_chunks <- split(1:n_subj, ceiling(seq_along(1:n_subj) / 10))

plots <- lapply(subject_chunks, function(chunk) plot_subjects(df %>% filter(cohort == "vmp1"), chunk, bin = 7))
plots
```

```{r, fig.height=7,fig.width=12, message=F, error=F,warning=F}
subs = unique(df %>% filter(cohort == "vmp2"& !subject %in% removers_vmp2) %>% .$subject)
n_subj <- length(subs)
subject_chunks <- split(1:n_subj, ceiling(seq_along(1:n_subj) / 10))

plots <- lapply(subject_chunks, function(chunk) plot_subjects(df %>% filter(cohort == "vmp2") %>% mutate(subject = as.numeric(as.factor(subject))), chunk, bin = 7))
plots
```

```{r, fig.height=7,fig.width=12}

df1 = df %>% filter(!subject %in% c("16", "167")) %>% filter(cohort == "vmp1") %>% 
  filter(subject < 50) %>% 
  mutate(X_scaled = (X - mean(X)) / sd(X))

df1$subject = as.numeric(as.factor(df1$subject))

t_p_s = df1 %>% group_by(subject) %>% summarize(n = n())


ends <- cumsum(t_p_s$n)

# Calculate the start points
starts <- c(1, head(ends, -1) + 1)

# mod = cmdstanr::cmdstan_model(here::here("Stanmodels","ss","ACC_Bin_hier_Correct.stan"))
mod = cmdstanr::cmdstan_model(here::here("Stanmodels","ss","ACC_Bin_hier_Correct_rtstim.stan"))

datastan = list(N = nrow(df1),
                S = length(unique(df1$subject)),
                starts = starts,
                minRT = df1 %>% group_by(subject) %>% summarize(minRT = min(RT)) %>% .$minRT,
                ends = ends,
                t_p_s = t_p_s$n,
                X = df1$X,
                X_scaled = (df1$X - mean(df1$X)) / sd(df1$X),
                S_id = df1$subject,
                RT = df1$RT,
                ACC = df1$Correct,
                K = length(unique(df1$Confidence)),
                Conf = df1$Confidence,
                binom_y = df1$Correct)



cor <-mod$sample(
  data = datastan,
  refresh = 10,
  iter_sampling = 500,
  iter_warmup = 500,
  adapt_delta = 0.99,
  max_treedepth = 13,
  init  = 0,
  parallel_chains = 4)

cor$save_object(here::here("Saved models","VMP_BA_ext_ses1_cohort1_s_50.rds"))


mod = cmdstan_model(here::here("Stanmodels","ss","lapse_free","lapse_free_full.stan"))


compar <-mod$sample(
  data = datastan,
  refresh = 10,
  iter_sampling = 500,
  iter_warmup = 500,
  adapt_delta = 0.99,
  max_treedepth = 13,
  init  = 0,
  parallel_chains = 4)

compar$save_object(here::here("Saved models","lapse_free_VMP_ext_ses1_cohort1_s_50.rds"))




```





```{r, fig.height=7,fig.width=12}
preds = Get_predictive_ACC_hier(fit,df1,20)

bin_pure = Plot_psychometric_ACC_hier(preds,df1)

bin_pure

Plot_psychometric_resp_hier(preds,df1)
```






```{r, fig.height=7, fig.width=12, warning=FALSE}
rt = Plot_RT_hier(preds,df1, bin = 7)
rt
```

```{r, fig.height=7,fig.width=12, warning=FALSE}
conf = Plot_Conf_ACC_hier(preds,df1, bin = 7)
conf
```



```{r, fig.height=7,fig.width=12, warning=FALSE}

predictions = Get_predictive_group(fit ,df1,10)

plots = Plot_group_predictive_psycho(predictions, df1)

plots


ggsave(here::here("Extero_VMP1_marginal_means.tiff"), plots$plot_combined, dpi = 100, width = 12, height = 8)


```


```{r}

get_psychometric = function(fit, model){
  
  
  as_draws_df(fit$draws(c("alpha","beta","lapse"))) %>% 
    select(-contains(".")) %>%
    mutate(draw = 1:n()) %>%
    pivot_longer(-draw) %>%
    extract(name, into = c("variable", "subject"),
            regex = "([a-zA-Z0-9_]+)\\[(\\d+)\\]", convert = TRUE) %>% 
    mutate(subject = as.factor(subject),
           model = model)
  
}

library(ggridges)
library(ggh4x)

get_psychometric(fit, "confidence")%>% 
    ggplot(aes(y = subject, x = value))+
    geom_density_ridges(aes(y = subject, x = value),rel_min_height = 0.01, alpha = 0.5)+
    facet_wrap(~variable, scales = "free")+
    facetted_pos_scales(
        x = list(
            variable == "alpha"  ~ scale_x_continuous(limits = c(-10, 10), breaks = seq(-10, 10, 5)),
            variable == "beta"   ~ scale_x_continuous(limits = c(0, 0.7), breaks = seq(0, 0.7, 0.2)),
            variable == "lapse"  ~ scale_x_continuous(limits = c(0, 0.5), breaks = seq(0, 0.5, 0.1))
        )
    ) +
    theme_classic(base_size = 16)

df_summary = get_psychometric(fit, "confidence") %>%
  group_by(variable, subject) %>%
  summarise(mean = mean(value),
            lower = quantile(value, 0.05),
            upper = quantile(value, 0.95),
            .groups = "drop")

ggplot(df_summary, aes(y = subject, x = mean)) +
  geom_pointrange(aes(xmin = lower, xmax = upper), fatten = 0.5) +
  facet_wrap(~variable, scales = "free_x") +
  theme_classic(base_size = 14)

```


```{r}

get_psychometric = function(fit, model){
  
  
  as_draws_df(fit$draws(c("meta_un","meta_bias"))) %>% 
    select(-contains(".")) %>%
    mutate(draw = 1:n()) %>%
    pivot_longer(-draw) %>%
    extract(name, into = c("variable", "subject"),
            regex = "([a-zA-Z0-9_]+)\\[(\\d+)\\]", convert = TRUE) %>% 
    mutate(subject = as.factor(subject),
           model = model)
  
}

library(ggridges)
library(ggh4x)

# get_psychometric(fit, "confidence")%>% 
#     ggplot(aes(y = subject, x = value))+
#     geom_density_ridges(aes(y = subject, x = value),rel_min_height = 0.01, alpha = 0.5)+
#     facet_wrap(~variable, scales = "free")+
#     facetted_pos_scales(
#         x = list(
#             variable == "alpha"  ~ scale_x_continuous(limits = c(-10, 10), breaks = seq(-10, 10, 5)),
#             variable == "beta"   ~ scale_x_continuous(limits = c(0, 0.7), breaks = seq(0, 0.7, 0.2)),
#             variable == "lapse"  ~ scale_x_continuous(limits = c(0, 0.5), breaks = seq(0, 0.5, 0.1))
#         )
#     ) +
#     theme_classic(base_size = 16)

df_summary = get_psychometric(fit, "confidence") %>%
  group_by(variable, subject) %>%
  summarise(mean = mean(value),
            lower = quantile(value, 0.05),
            upper = quantile(value, 0.95),
            .groups = "drop")

ggplot(df_summary, aes(y = subject, x = mean)) +
  geom_pointrange(aes(xmin = lower, xmax = upper), fatten = 0.5) +
  facet_wrap(~variable, scales = "free_x") +
  theme_classic(base_size = 14)+
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank())



```
## vmp2 

```{r}
df1 = df %>% filter(!subject %in% removers_vmp2 )%>% filter(cohort == "vmp2")%>% 
  mutate(X_scaled = (X - mean(X)) / sd(X))

df1$subject = as.numeric(as.factor(df1$subject))

t_p_s = df1 %>% group_by(subject) %>% summarize(n = n())


ends <- cumsum(t_p_s$n)

# Calculate the start points
starts <- c(1, head(ends, -1) + 1)

# mod = cmdstanr::cmdstan_model(here::here("Stanmodels","ss","ACC_Bin_hier_Correct.stan"))
mod = cmdstanr::cmdstan_model(here::here("Stanmodels","ss","ACC_Bin_hier_Correct_rtstim.stan"))

datastan = list(N = nrow(df1),
                S = length(unique(df1$subject)),
                starts = starts,
                minRT = df1 %>% group_by(subject) %>% summarize(minRT = min(RT)) %>% .$minRT,
                ends = ends,
                t_p_s = t_p_s$n,
                X = df1$X,
                S_id = df1$subject,
                RT = df1$RT,
                ACC = df1$Correct,
                K = length(unique(df1$Confidence)),
                Conf = df1$Confidence,
                binom_y = df1$Correct)


cor <-mod$sample(
  data = datastan,
  refresh = 10,
  iter_sampling = 500,
  iter_warmup = 500,
  adapt_delta = 0.99,
  max_treedepth = 12,
  init  = 0,
  parallel_chains = 4)

# cor$save_object(here::here("Saved models","VMP_BA_ext_ses1_cohort2.rds"))
```




```{r, fig.height=7,fig.width=12}
preds = Get_predictive_ACC_hier(fit,df1,20)

bin_pure = Plot_psychometric_ACC_hier(preds,df1)

bin_pure

Plot_psychometric_resp_hier(preds,df1)
```






```{r, fig.height=7, fig.width=12, warning=FALSE}
rt = Plot_RT_hier(preds,df1, bin = 7)
rt
```

```{r, fig.height=7,fig.width=12, warning=FALSE}
conf = Plot_Conf_ACC_hier(preds,df1, bin = 7)
conf
```



```{r, fig.height=7,fig.width=12, warning=FALSE}

predictions = Get_predictive_group(fit,df1,2000)

plots = Plot_group_predictive_psycho(predictions, df1)

plots


ggsave(here::here("Extero_VMP2_marginal_means.tiff"), plots$plot_combined, dpi = 100, width = 12, height = 8)

```


```{r}

get_psychometric = function(fit, model){
  
  
  as_draws_df(fit$draws(c("alpha","beta","lapse"))) %>% 
    select(-contains(".")) %>%
    mutate(draw = 1:n()) %>%
    pivot_longer(-draw) %>%
    extract(name, into = c("variable", "subject"),
            regex = "([a-zA-Z0-9_]+)\\[(\\d+)\\]", convert = TRUE) %>% 
    mutate(subject = as.factor(subject),
           model = model)
  
}

library(ggridges)
library(ggh4x)

# get_psychometric(fit, "confidence")%>% 
#     ggplot(aes(y = subject, x = value))+
#     geom_density_ridges(aes(y = subject, x = value),rel_min_height = 0.01, alpha = 0.5)+
#     facet_wrap(~variable, scales = "free")+
#     facetted_pos_scales(
#         x = list(
#             variable == "alpha"  ~ scale_x_continuous(limits = c(-10, 10), breaks = seq(-10, 10, 5)),
#             variable == "beta"   ~ scale_x_continuous(limits = c(0, 0.7), breaks = seq(0, 0.7, 0.2)),
#             variable == "lapse"  ~ scale_x_continuous(limits = c(0, 0.5), breaks = seq(0, 0.5, 0.1))
#         )
#     ) +
#     theme_classic(base_size = 16)

df_summary = get_psychometric(fit, "confidence") %>%
  group_by(variable, subject) %>%
  summarise(mean = mean(value),
            lower = quantile(value, 0.05),
            upper = quantile(value, 0.95),
            .groups = "drop")

ggplot(df_summary, aes(y = subject, x = mean)) +
  geom_pointrange(aes(xmin = lower, xmax = upper), fatten = 0.5) +
  facet_wrap(~variable, scales = "free_x") +
  theme_classic(base_size = 14)

```

```{r}

get_psychometric = function(fit, model){
  
  
  as_draws_df(fit$draws(c("meta_un","meta_bias"))) %>% 
    select(-contains(".")) %>%
    mutate(draw = 1:n()) %>%
    pivot_longer(-draw) %>%
    extract(name, into = c("variable", "subject"),
            regex = "([a-zA-Z0-9_]+)\\[(\\d+)\\]", convert = TRUE) %>% 
    mutate(subject = as.factor(subject),
           model = model)
  
}

library(ggridges)
library(ggh4x)

# get_psychometric(fit, "confidence")%>% 
#     ggplot(aes(y = subject, x = value))+
#     geom_density_ridges(aes(y = subject, x = value),rel_min_height = 0.01, alpha = 0.5)+
#     facet_wrap(~variable, scales = "free")+
#     facetted_pos_scales(
#         x = list(
#             variable == "alpha"  ~ scale_x_continuous(limits = c(-10, 10), breaks = seq(-10, 10, 5)),
#             variable == "beta"   ~ scale_x_continuous(limits = c(0, 0.7), breaks = seq(0, 0.7, 0.2)),
#             variable == "lapse"  ~ scale_x_continuous(limits = c(0, 0.5), breaks = seq(0, 0.5, 0.1))
#         )
#     ) +
#     theme_classic(base_size = 16)

df_summary = get_psychometric(fit, "confidence") %>%
  group_by(variable, subject) %>%
  summarise(mean = mean(value),
            lower = quantile(value, 0.05),
            upper = quantile(value, 0.95),
            .groups = "drop")

ggplot(df_summary, aes(y = subject, x = mean)) +
  geom_pointrange(aes(xmin = lower, xmax = upper), fatten = 0.5) +
  facet_wrap(~variable, scales = "free_x") +
  theme_classic(base_size = 14)+
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank())



```

